version: "3.8"

services:
  auth0:
    image: wiremock/wiremock:2.30.0
    volumes:
      - ./dockerfiles/wiremock/__files:/home/wiremock/__files
      - ./dockerfiles/wiremock/mappings:/home/wiremock/mappings
    command: --port 8080 --verbose
    expose:
      - "8080"
    ports:
      - "8080:8080"
