name: Main Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Check out the code
        uses: actions/checkout@v3

      - name: Check for linting errors
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.46.2
          args: -c .golangci.yml --allow-parallel-runners

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Check out the code
        uses: actions/checkout@v3

      - name: Run tests
        run: make test

      - name: Update codecov report
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.out
          fail_ci_if_error: false
          verbose: true
